apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    {{- include "go-api.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
